module.exports = {
	plugins: [
		'stylelint-codeguide',
		'stylelint-order',
	],
	rules: {
		// ERRORS

		'alpha-value-notation': 'number',
		'annotation-no-unknown': true,
		'at-rule-empty-line-before': ['always', {
			ignore: ['after-comment', 'inside-block'],
		}],
		'at-rule-no-unknown': true,
		'at-rule-no-vendor-prefix': true,
		'block-no-empty': true,
		'codeguide/at-rule-name-case': 'lower',
		'codeguide/at-rule-name-space-after': 'always',
		'codeguide/at-rule-semicolon-newline-after': 'always',
		'codeguide/at-rule-semicolon-space-before': 'never',
		'codeguide/block-closing-brace-empty-line-before': 'never',
		'codeguide/block-closing-brace-newline-after': 'always',
		'codeguide/block-closing-brace-space-before': 'always-single-line',
		'codeguide/block-opening-brace-newline-after': 'always-multi-line',
		'codeguide/block-opening-brace-space-after': 'always-single-line',
		'codeguide/block-opening-brace-space-before': 'always-multi-line',
		'codeguide/color-hex-case': 'upper',
		'codeguide/declaration-bang-space-after': 'never',
		'codeguide/declaration-bang-space-before': 'always',
		'codeguide/declaration-block-semicolon-newline-after': 'always-multi-line',
		'codeguide/declaration-block-semicolon-newline-before': 'never-multi-line',
		'codeguide/declaration-block-semicolon-space-after': 'always-single-line',
		'codeguide/declaration-block-semicolon-space-before': 'never-single-line',
		'codeguide/declaration-colon-newline-after': 'always-multi-line',
		'codeguide/declaration-colon-space-after': 'always-single-line',
		'codeguide/declaration-colon-space-before': 'never',
		'codeguide/function-comma-newline-after': 'always-multi-line',
		'codeguide/function-comma-newline-before': 'never-multi-line',
		'codeguide/function-comma-space-after': 'always-single-line',
		'codeguide/function-comma-space-before': 'never',
		'codeguide/function-max-empty-lines': 2,
		'codeguide/function-parentheses-newline-inside': 'always-multi-line',
		'codeguide/function-parentheses-space-inside': 'never-single-line',
		'codeguide/function-whitespace-after': 'always',
		'codeguide/indentation': 'tab',
		'codeguide/max-empty-lines': 2,
		'codeguide/max-line-length': 120,
		'codeguide/media-feature-colon-space-after': 'always',
		'codeguide/media-feature-colon-space-before': 'never',
		'codeguide/media-feature-name-case': 'lower',
		'codeguide/media-feature-parentheses-space-inside': 'never',
		'codeguide/media-feature-range-operator-space-after': 'always',
		'codeguide/media-feature-range-operator-space-before': 'always',
		'codeguide/media-query-list-comma-newline-after': 'always-multi-line',
		'codeguide/media-query-list-comma-newline-before': 'never-multi-line',
		'codeguide/media-query-list-comma-space-after': 'always-single-line',
		'codeguide/media-query-list-comma-space-before': 'never',
		'codeguide/no-extra-semicolons': true,
		'codeguide/number-leading-zero': 'always',
		'codeguide/number-no-trailing-zeros': true,
		'codeguide/property-case': 'lower',
		'codeguide/selector-attribute-brackets-space-inside': 'never',
		'codeguide/selector-attribute-operator-space-after': 'never',
		'codeguide/selector-attribute-operator-space-before': 'never',
		'codeguide/selector-combinator-space-after': 'always',
		'codeguide/selector-combinator-space-before': 'always',
		'codeguide/selector-descendant-combinator-no-non-space': true,
		'codeguide/selector-list-comma-newline-after': 'always-multi-line',
		'codeguide/selector-list-comma-newline-before': 'never-multi-line',
		'codeguide/selector-list-comma-space-after': 'always-single-line',
		'codeguide/selector-list-comma-space-before': 'never',
		'codeguide/selector-max-empty-lines': 0,
		'codeguide/selector-pseudo-class-case': 'lower',
		'codeguide/selector-pseudo-class-parentheses-space-inside': 'never',
		'codeguide/selector-pseudo-element-case': 'lower',
		'codeguide/string-quotes': 'double',
		'codeguide/unit-case': 'lower',
		'codeguide/value-list-comma-newline-after': 'always-multi-line',
		'codeguide/value-list-comma-newline-before': 'never-multi-line',
		'codeguide/value-list-comma-space-after': 'always-single-line',
		'codeguide/value-list-comma-space-before': 'never',
		'codeguide/value-list-max-empty-lines': 0,
		'color-function-notation': 'legacy',
		'color-hex-alpha': 'never',
		'color-hex-length': 'short',
		'color-named': 'never',
		'color-no-hex': true,
		'color-no-invalid-hex': true,
		'comment-no-empty': true,
		'comment-whitespace-inside': 'always',
		'custom-property-empty-line-before': 'never',
		'custom-property-no-missing-var-function': true,
		'declaration-block-no-duplicate-custom-properties': true,
		'declaration-block-no-duplicate-properties': true,
		'declaration-block-no-redundant-longhand-properties': true,
		'declaration-block-no-shorthand-property-overrides': true,
		'declaration-block-single-line-max-declarations': 1,
		'declaration-empty-line-before': 'never',
		'declaration-no-important': true,
		'declaration-property-value-no-unknown': true,
		'font-family-name-quotes': 'always-where-recommended',
		'font-family-no-duplicate-names': true,
		'font-family-no-missing-generic-family-keyword': true,
		'font-weight-notation': 'named-where-possible',
		'function-calc-no-unspaced-operator': true,
		'function-disallowed-list': ['calc'],
		'function-linear-gradient-no-nonstandard-direction': true,
		'function-name-case': 'lower',
		'function-no-unknown': true,
		'function-url-quotes': 'always',
		'hue-degree-notation': 'number',
		'import-notation': 'string',
		'keyframe-block-no-duplicate-selectors': true,
		'keyframe-declaration-no-important': true,
		'length-zero-no-unit': true,
		'max-nesting-depth': 2,
		'media-feature-name-no-unknown': true,
		'media-feature-name-no-vendor-prefix': true,
		'media-feature-name-value-no-unknown': true,
		'media-query-no-invalid': true,
		'named-grid-areas-no-invalid': true,
		'no-duplicate-at-import-rules': true,
		'no-duplicate-selectors': true,
		'no-empty-source': true,
		'no-invalid-position-at-import-rule': true,
		'no-irregular-whitespace': true,
		'no-unknown-animations': true,
		'number-max-precision': 3,
		'order/order': [
			'at-rules',
			'custom-properties',
			'dollar-variables',
			'declarations',
			'rules',
		],
		'order/properties-alphabetical-order': true,
		'property-disallowed-list': ['float'],
		'property-no-unknown': true,
		'property-no-vendor-prefix': true,
		'rule-empty-line-before': ['always-multi-line', {
			except: ['first-nested'],
			ignore: ['after-comment'],
		}],
		'selector-anb-no-unmatchable': true,
		'selector-attribute-quotes': 'always',
		'selector-class-pattern': ['^[a-z]', {
			resolveNestedSelectors: true,
		}],
		'selector-max-attribute': 0,
		'selector-max-combinators': 0,
		'selector-max-id': 0,
		'selector-max-pseudo-class': 2,
		'selector-max-specificity': '0,4,0',
		'selector-max-type': 0,
		'selector-max-universal': 0,
		'selector-no-qualifying-type': true,
		'selector-no-vendor-prefix': true,
		'selector-not-notation': 'simple',
		'selector-pseudo-class-no-unknown': [true, {ignorePseudoClasses: ['global']}],
		'selector-pseudo-element-colon-notation': 'double',
		'selector-pseudo-element-no-unknown': true,
		'selector-type-case': 'lower',
		'selector-type-no-unknown': true,
		'shorthand-property-no-redundant-values': true,
		'string-no-newline': true,
		'time-min-milliseconds': 100,
		'unit-disallowed-list': ['em'],
		'unit-no-unknown': true,
		'value-keyword-case': ['lower', {
			camelCaseSvgKeywords: true,
			ignoreKeywords: [
				'Arial', 'Consolas', 'Courier', 'Helvetica', 'Inconsolata', 'Menlo', 'Roboto',
			],
		}],
		'value-no-vendor-prefix': true,

		// WARNINGS

		'comment-word-disallowed-list': [['/^TODO/'], {severity: 'warning'}],
		'selector-max-compound-selectors': [3, {severity: 'warning'}],

		// DISABLED

		'at-rule-allowed-list': null,
		'at-rule-disallowed-list': null,
		'at-rule-property-required-list': null,
		'codeguide/at-rule-name-newline-after': null,
		'codeguide/block-closing-brace-newline-before': null,
		'codeguide/block-closing-brace-space-after': null,
		'codeguide/block-opening-brace-newline-before': null,
		'codeguide/declaration-block-trailing-semicolon': null,
		'codeguide/linebreaks': null,
		'codeguide/no-empty-first-line': null,
		'codeguide/no-eol-whitespace': null,
		'codeguide/no-missing-end-of-source-newline': null,
		// This rule seems broken
		'codeguide/unicode-bom': 'never',
		'comment-empty-line-before': null,
		// This rule cannot be turned off with 'null'
		// 'comment-pattern': null,
		'custom-media-pattern': null,
		'custom-property-pattern': null,
		'declaration-property-max-values': null,
		'declaration-property-unit-allowed-list': null,
		'declaration-property-unit-disallowed-list': null,
		'declaration-property-value-allowed-list': null,
		'declaration-property-value-disallowed-list': null,
		'function-allowed-list': null,
		'function-url-no-scheme-relative': null,
		'function-url-scheme-allowed-list': null,
		'function-url-scheme-disallowed-list': null,
		'keyframe-selector-notation': null,
		'keyframes-name-pattern': null,
		'media-feature-name-allowed-list': null,
		'media-feature-name-disallowed-list': null,
		'media-feature-name-unit-allowed-list': null,
		'media-feature-name-value-allowed-list': null,
		'media-feature-range-notation': null,
		'no-descending-specificity': null,
		'no-invalid-double-slash-comments': null,
		'no-unknown-custom-properties': null,
		'order/properties-order': null,
		'property-allowed-list': null,
		'rule-selector-property-disallowed-list': null,
		'selector-attribute-name-disallowed-list': null,
		'selector-attribute-operator-allowed-list': null,
		'selector-attribute-operator-disallowed-list': null,
		'selector-combinator-allowed-list': null,
		'selector-combinator-disallowed-list': null,
		'selector-disallowed-list': null,
		'selector-id-pattern': null,
		'selector-max-class': null,
		'selector-nested-pattern': null,
		'selector-pseudo-class-allowed-list': null,
		'selector-pseudo-class-disallowed-list': null,
		'selector-pseudo-element-allowed-list': null,
		'selector-pseudo-element-disallowed-list': null,
		'unit-allowed-list': null,
	},
};
