name: Release

on:
    push:
        branches:
            - beta
            - master

permissions:
    contents: read

jobs:
  Release:
    runs-on: ubuntu-latest
    permissions:
        contents: write
        issues: write
        pull-requests: write
        id-token: write
    steps:
    - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4

    - uses: pnpm/action-setup@v2.4.0
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm i

    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: pnpm semantic-release
